version: '2'
services:
  database:
    extends:
      file: ../common/docker-compose.yml
      service: database
    environment:
      POSTGRES_USER: "postgres_dev"
      POSTGRES_PASSWORD: "p0stgr@s_dev"
      POSTGRES_DB:       "eagle_eye_dev"
  configserver:
    extends:
      file: ../common/docker-compose.yml
      service: configserver
  licensingservice:
     image: ch3-thoughtmechanix/licensing-service
     ports:
       - "10001:10001"
     environment:
       PROFILE: "dev"
       SERVER_PORT: "10001"
       CONFIGSERVER_URI: "http://configserver:8888"
       CONFIGSERVER_PORT:   "8888"
       DATABASESERVER_PORT: "5432"