version: '2'
services:
  eurekaserver:
    image:   johncarnell/tmx-eurekasvr:chapter5
    ports:
      - "8761:8761"
  configserver:
    image: johncarnell/tmx-confsvr:chapter3
    ports:
       - "10000:10000"
    environment:
      ENCRYPT_KEY: "IMSYMMETRIC"
  database:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "p0stgr@s"
      POSTGRES_DB:       "eagle_eye_local"
  licensingservice:
    image: johncarnell/tmx-licensing-service:chapter3
    ports:
      - "10001:10001"
    environment:
      PROFILE: "default"
      SERVER_PORT: "10001"
      CONFIGSERVER_URI: "http://configserver:10000"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      CONFIGSERVER_PORT:   "10000"
      DATABASESERVER_PORT: "5432"
      EUREKASERVER_PORT:   "8761"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  organizationservice:
    image: johncarnell/tmx-organization-service:chapter5
    ports:
      - "10002:10002"
    environment:
      PROFILE: "default"
      SERVER_PORT: "10002"
      CONFIGSERVER_URI: "http://configserver:10000"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      CONFIGSERVER_PORT:   "10000"
      DATABASESERVER_PORT: "5432"
      EUREKASERVER_PORT:   "8761"
      ENCRYPT_KEY:       "IMSYMMETRIC"
